<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function helper_theme($existing, $type, $theme, $path) {
  return [
    //Cats edit form
    'cats' => [
      'variables' => [
        'form' => []
      ],
    ],
    //Cats display all records DB table 'helper'
    'cats-view' => [
      'variables' => [
        'form' => [
          'cats' => []
        ],
      ],
    ],
  ];
}
