features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
enable_darkmode: '1'
preset_accent_color: orange
accent_color: ''
preset_focus_color: gin
focus_color: ''
high_contrast_mode: 1
classic_toolbar: classic
secondary_toolbar_frontend: 0
layout_density: small
show_description_toggle: 1
show_user_theme_settings: 1
